gcc-focal-images:
  template: 'Dockerfile.gcc-focal.j2'
  image: 'gcc'
  versions: ['4.8', '4.9', '5', '6', '7', '8']

gcc-jammy-images:
  template: 'Dockerfile.gcc-jammy.j2'
  image: 'gcc'
  versions: ['9', '10', '11', '12', 'latest']
