{%extends 'Dockerfile.base.j2' %}
{% set codename='focal' %}

{% import 'apt_macros.j2' as apt %}

{% block repos %}
    {{ apt.add_ubuntu_repo('bionic', ['main', 'universe']) }}
    {{ apt.add_ubuntu_repo('xenial', ['main', 'universe']) }}
    {{ apt.add_ubuntu_repo('xenial-updates', ['main', 'universe']) }}
{% endblock %}

{% block packages %}
    {{ super() }}
    libidn11
{% endblock %}
