name: Build and publish Docker images

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  image_json_ci_base_jammy:
    name: Build and publish image json-ci-base-jammy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the GitHub Container registry
        if: true && github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/json-ci-base-jammy
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long

      - name: Build and push Docker image json-ci-base-jammy
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.cuda
          push: ${{ true && github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha
          target: json-ci-base-jammy
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  image_json_ci_cuda_11_7:
    name: Build and publish image json-ci-cuda-11.7
    runs-on: ubuntu-latest
    needs: [image_json_ci_base_jammy]
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the GitHub Container registry
        if: true && github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/json-ci-cuda-11.7
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long

      - name: Build and push Docker image json-ci-cuda-11.7
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.cuda
          push: ${{ true && github.event_name != 'pull_request' }}
          cache-from: type=gha
          target: json-ci-cuda-11.7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  image_json_ci_base_focal:
    name: Build and publish image json-ci-base-focal
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the GitHub Container registry
        if: true && github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/json-ci-base-focal
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long

      - name: Build and push Docker image json-ci-base-focal
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.icpc
          push: ${{ true && github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha
          target: json-ci-base-focal
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  image_json_ci_icpc_2022_1_0:
    name: Build and publish image json-ci-icpc-2022.1.0
    runs-on: ubuntu-latest
    needs: [image_json_ci_base_focal]
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the GitHub Container registry
        if: true && github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/json-ci-icpc-2022.1.0
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long

      - name: Build and push Docker image json-ci-icpc-2022.1.0
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.icpc
          push: ${{ true && github.event_name != 'pull_request' }}
          cache-from: type=gha
          target: json-ci-icpc-2022.1.0
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
